### ISSUE TITLE
[Feature Request / Question] Ready to go framework ?

### ISSUE THREAD

**Issue by Shotman** [ikari-js/ikari#15]
I came across ikari recently and I'm wondering how mature it is, and if the roadmap plans to create a complete framework like Symfony or Laravel in the PHP world ? 
With best practices, folder structure, built in ORM/Migrations, front end solution, templating  etc

**Comment by aaydin-tr** [comment]
Hello, first of all, thank you for your question. ikari is currently mature enough to develop an end-to-end product. When used with the built-in dependency injection system and official middleware, it has a robust infrastructure.

In terms of performance, it is on par with other well-known frameworks. Additionally, I'm continually working on performance improvements.

I have a vision of making ikari a complete framework, and I developed the dependency injection system with that in mind. However, this is not my primary focus right now. At this stage, it seems more reasonable to create a framework that works seamlessly with existing structures and those using decorators, rather than rebuilding these systems from scratch. For instance, making ikari compatible with TypeORM as a plugin.

Of course, I should note that I developed ikari based on my own needs and will continue to do so. Therefore, these kinds of developments will accelerate as ikari's usage increases and I receive more feedback.

**Comment by Shotman** [comment]
> I have a vision of making ikari a complete framework, and I developed the dependency injection system with that in mind. However, this is not my primary focus right now. At this stage, it seems more reasonable to create a framework that works seamlessly with existing structures and those using decorators, rather than rebuilding these systems from scratch. For instance, making ikari compatible with TypeORM as a plugin.

That's exactly what I had in mind, the way the PHP world does it. To stay on the ORM part for Symfony is Doctrine, for Laravel it's Eloquent. 

And once each bricks is chosen make them all work together and provide a boilerplate with everything you need to start building an complete app.
 Ikari for the HTTP side of things, an ORM, a templating engine etc

**Comment by aaydin-tr** [comment]
It's great that we're on the same page; I'm open to any contributions in this direction. 🙏
